### PR TITLE
Fix wide character padding

### LINKED ISSUE #27: Display issue with Chinese
Hi, thanks for developing such an awesome script. I didn't test for other languages, but when files name with English and Chinese, the output of `ls` will be disordered. Hope this can be fixed later.
Snipaste_2019-08-11_16-22-30

### PR DESCRIPTION
**Pull request by shiena**
fix #27 

`$Host.UI.RawUI.LengthInBufferCells` is here
https://github.com/PowerShell/PowerShell/blob/v7.0.0/src/System.Management.Automation/FormatAndOutput/common/ILineOutput.cs#L68-L89

### CODE REVIEW

**Comment by joonro** [comment]
Hi -

Thank you very much for the PR. I just checked this out and tried it, but I did not see any difference in output for Korean file names - could you please show me the difference in your end?

**Comment by shiena** [comment]
Thanks for checking. Padding gaps have been resolved in my environment.

**patch version**
image

**original version**
image

**Comment by joonro** [comment]
Thanks for the screenshots. I installed your commit, and for some reason, I'm still getting not aligned file names. I will check it out again tomorrow. By the way, could you please let me know of your PowerShell version?

image

**Comment by shiena** [comment]
I understand why it doesn't work in your environment.
Only 6.2.4 works differently.
5.1 and 7.0 are correct padding.

image
image
image

**Comment by joonro** [comment]
That is very funny. I just installed pwsh 7.0 and the padding is correct. I will merge this shortly. Thank you very much!!

**Pull request merged**
