### PR TITLE
Removing additional newline for Get-ChildItemColorWide

### PR DESCRIPTION
**Pull request by fenneh**
Addressing #17 

Tested on varying sizes of console with varying numbers and types of files.

### CODE REVIEW

**Comment by musm** [comment]
cc 
@joonro

**Comment by musm** [comment]
BTW I tried modifying the `psd1` file, however powershell doesn't seem to be picking up local changes I have made to the module. Any idea on how to get powershell to pick up local changes to a module?

**Comment by joonro** [comment]
Hi - 

I'm very sorry for the late reply. In my machine, I'm actually getting two empty lines with `Get-ChildItemColor`, and only one empty line with `Get-ChildItemColorFormatWide`. Could you please actually provide a screenshot of what is going on? Thank you!

2018-10-29 22_32_47-posh git get-childitemcolor master

**Comment by musm** [comment]
Joonro I see the same as you. Can we fix this so we consistently only have 1 newline?

**Comment by joonro** [comment]
Unfortunately no - `Get-ChildItemColor` uses `Get-ChildItem` -- it just changes the colors. Since `Get-ChildItem` yields two lines before and after its output, currently the only thing I can do to make things consistent is adding additional lines to `Get-ChildItemColorFormatWide` - that is what happens with native `Get-ChildItem | Format-Wide -Column 3` as well.

**Comment by musm** [comment]
It should be able to manually strip the last end line in th ebuffer and then display it

**Comment by joonro** [comment]
Hi -

Sorry, but I decided to close this PR. I try to match the default behavior of `Get-ChildItem` and `Get-ChildItem | Format-Wide` as much as possible, especially for the default behavior (I'm aware that actually `Get-ChildItem | Format-Wide` has 3 newlines instead of 2, but in this case I followed `Get-ChildItem`).  

If you really want this, you can make it optional --- I would be happy to merge that PR. Again I'm sorry that it took me a long time to reply.

**Comment by joonro** [comment]
Hi, 

Never mind. I just implemented this - you can use `$Global:GetChildItemColorVerticalSpace` to modify how many vertical line spaces you want to have. The default is 1 so it should be what you want. Hope this works for you!

**Comment by fenneh** [comment]
Hah - No worries. Totally forgot about this :)

**Pull request closed without merging**
