### PR TITLE
+ support -recurse option

### PR DESCRIPTION
**Pull request by gcollic**
When using the function with `-recurse` option, only the first directory was showing

### CODE REVIEW

**Comment by gcollic** [comment]
I also added an automatic number of columns depending on file name lengths (I can do separated pull requests if needed)

**Comment by joonro** [comment]
Thank you so much for the PR - could you please let me know how to replicate `-recurse` part? I rarely use that option and I did not understand what you meant.

**Comment by gcollic** [comment]
For example, with this tree structure :

```
|   file.txt
+---f1
|   |   file.txt
|   +---f1.1
|   |       file.txt
|   \---f1.2
\---f2
        file.txt
```

`Get-ChildItem -recurse` should give :

```
    Directory: C:\foo

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       18/02/2016     13:35                f1
d-----       18/02/2016     13:35                f2
-a----       18/02/2016     13:33              0 file.txt

    Directory: C:\foo\f1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       18/02/2016     13:33                f1.1
d-----       18/02/2016     13:32                f1.2
-a----       18/02/2016     13:33              0 file.txt

    Directory: C:\foo\f1\f1.1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       18/02/2016     13:33              0 file.txt

    Directory: C:\foo\f2

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       18/02/2016     13:35              0 file.txt
```

but `Get-ChildItem-Color -recurse` was giving something like :

```
    Directory: C:\foo

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       18/02/2016     13:35                f1
d-----       18/02/2016     13:35                f2
-a----       18/02/2016     13:33              0 file.txt
d-----       18/02/2016     13:33                f1.1
d-----       18/02/2016     13:32                f1.2
-a----       18/02/2016     13:33              0 file.txt
-a----       18/02/2016     13:33              0 file.txt
-a----       18/02/2016     13:35              0 file.txt
```

**Comment by gcollic** [comment]
And for the second commit (which should have been another PR but I forgot to do feature branching), it adds dynamic column number, for when you have some big file name and want to see them entirely using only 1 column, or the opposite case when you are in a folder with a lot of files with tiny names (such as a `.git/objects` folder in a git repo), it's a bit of an extreme case but I prefer to have 13 columns rather than 3 in that case :

```
\.git\objects> Get-ChildItem-Format-Wide
00    01    02    03    04    06    07    08    0a    0b    0c    0d    0e
0f    10    11    12    14    15    17    18    1a    1b    1c    1e    1f
20    21    22    23    24    26    28    29    2a    2c    2d    2e    2f
32    33    34    36    37    38    3a    3b    3c    3e    3f    40    41
42    43    45    46    48    4a    4b    4c    4d    4e    4f    50    52
53    54    55    56    57    58    5b    5d    5e    5f    60    61    62
63    64    65    67    68    69    6a    6b    6c    6e    6f    70    71
72    73    75    76    77    78    7c    7e    81    82    83    85    86
87    88    89    8a    8b    8c    8d    8e    8f    90    92    93    95
96    97    98    99    9a    9c    9e    9f    a2    a4    a5    a6    a8
aa    ab    ac    ad    ae    af    b3    b4    b5    b7    b8    b9    ba
bc    bd    bf    c0    c1    c2    c3    c5    c6    c7    c8    c9    ca
cb    cc    ce    cf    d0    d3    d4    d5    d6    d7    d8    d9    db
dd    de    e0    e1    e2    e3    e4    e5    e6    e7    e8    ea    ec
ed    ee    ef    f0    f1    f2    f3    f4    f5    f7    f8    fa    fb
fc    fd    fe    ff    info  pack
```

**Comment by joonro** [comment]
These look fantastic - merged. Thank you so much.

**Pull request merged**
